### ISSUE TITLE
error when installing pyfarmhash 0.2.1

### ISSUE THREAD

**Issue by blampe** [veelion/python-farmhash#4]
``````
$ pip install pyfarmhash==0.2.1
Downloading/unpacking pyfarmhash==0.2.1
  Downloading pyfarmhash-0.2.1.tar.gz (96kB): 96kB downloaded
  Storing download in cache at ...
  Running setup.py (path:.../env/build/pyfarmhash/setup.py) egg_info for package pyfarmhash
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File ".../env/build/pyfarmhash/setup.py", line 13, in <module>
        long_description=open('README.md', 'r').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File ".../env/build/pyfarmhash/setup.py", line 13, in <module>

    long_description=open('README.md', 'r').read(),

IOError: [Errno 2] No such file or directory: 'README.md'```
``````

**Comment by veelion** [comment]
fix at version 0.2.2
Thanks :)
